
language: java

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11

branches:
  only:
  - master

sudo: required
services:
  - docker

install: true # This runs the "true" command in the install phase; thus skipping install
before_script: cd java/pubsub
script:
  - |
    if [[ "$TRAVIS_BRANCH" == master && "$TRAVIS_PULL_REQUEST" == false && "$TRAVIS_JDK_VERSION" == "openjdk8" ]]
    then mvn package
    else mvn verify
    fi

cache:
  directories:
    - $HOME/.m2/repository/

notifications:
  slack: unauthed:82vtjYNF1hDzbe5oGeScrEEK

