# gcloud builds submit --config=cloudbuild.yaml .

timeout: 2200s
tags: ['gdg']

substitutions:
  _PROJECT_BUCKET: gdg-bristol-pubsub-artifacts

steps:
  - name: 'eu.gcr.io/${PROJECT_ID}/spring'
    args: ['appengine:deploy', '-Pdeb,rpm,docker,gcp']
    dir: 'java/pubsub'

  - name: gcr.io/cloud-builders/gsutil
    args: ['cp', 'java/pubsub/target/*.deb', 'gs://${_PROJECT_BUCKET}/deb']

images: ['eu.gcr.io/${PROJECT_ID}/gdg-pubsub']

artifacts:
  objects:
    location: 'gs://${_PROJECT_BUCKET}/artifacts'
    paths: ['java/pubsub/target/*.jar', 'java/pubsub/target/*.deb', 'java/pubsub/target/rpm/gdg-pubsub/RPMS/noarch/*.noarch.rpm']
