
steps:
  - name: 'eu.gcr.io/${PROJECT_ID}/spring'
    args: ['package', '-Pdeb,rpm,docker']
    dir: 'java/pubsub'

  - name: gcr.io/cloud-builders/gsutil
    args: ['cp', 'java/pubsub/target/*.jar', 'gs://seagulls-build-artifacts/jar/']
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp', 'java/pubsub/target/*.deb', 'gs://seagulls-build-artifacts/deb/']
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp', 'java/pubsub/target/rpm/gdg-pubsub/RPMS/noarch/*.noarch.rpm', 'gs://seagulls-build-artifacts/rpm/']

  - name: 'eu.gcr.io/${PROJECT_ID}/spring'
    args: ['appengine:deploy', '-DskipTests', '-Pgcp']
    dir: 'java/pubsub'

images: ['eu.gcr.io/${PROJECT_ID}/gdg-pubsub']

timeout: 2200s
tags: ['gdg']
