
steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package']
  dir: 'java/pubsub'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/pubsub', '.']
  dir: 'java/pubsub'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
  dir: 'java/pubsub/src/main/appengine'
images: ['gcr.io/$PROJECT_ID/gdg-pubsub']
timeout: '1600s'
tags: ['gdg']
