
steps:
  - name: 'eu.gcr.io/${PROJECT_ID}/mvn'
    args: ['package']
    dir: 'java/pubsub'
  - name: 'eu.gcr.io/${PROJECT_ID}/mvn'
    args: ['appengine:deploy', '-Pgcp', "-DskipTests", ""]
    dir: 'java/pubsub'

timeout: 1200s
tags: ['gdg']
options:
  machineType: 'N1_HIGHCPU_8'
  diskSizeGb: 50
