
runtime: java
env: flex

runtime_config:
  jdk: openjdk8

handlers:
  - url: /.*
    script: required but ignored WTF?

skip_files:
  - ^(.*/)?\.bak$

network:
  instance_tag: gdg-bristol

liveness_check:
  path: '/actuator/health'
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: '/actuator/health'
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

resources:
  cpu: 2
  memory_gb: 1.4
  disk_size_gb: 10

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6

#manual_scaling:
#  instances: 1

env_variables:
  BUCKET_NAME: 'testBucket'
  SPRING_PROFILES_ACTIVE: 'development'
  GDG_MESSAGE_TOPIC: 'testTopic'
  GDG_MESSAGE_SUBSCRIPTION: 'testSubscription'
