
spring:
  application:
    name: '@project.name@'

server:
  port: '${GDG_SERVER_PORT:8080}'

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: 'ALWAYS'
  server:
    address: '0.0.0.0'
    port: '${GDG_SERVER_PORT:8080}'
   
---

gdg:
  message:
    topic: '${GDG_MESSAGE_TOPIC:testTopic}'
    subscription: '${GDG_MESSAGE_SUBSCRIPTION:testSubscription}'
