version: '3'
services:
  cadvisor:
    ports:
      - 9080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always
    hostname: '{{.Node.Hostname}}'
    image: google/cadvisor
  prometheus:
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    depends_on:
      - cadvisor
      - node-exporter
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    image: prom/prometheus
  node-exporter:
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    restart: always
    image: prom/node-exporter
  zipkin:
    ports:
      - 9411:9411
    depends_on:
      - prometheus
    image: openzipkin/zipkin
  grafana:
    ports:
      - 3000:3000
    volumes:
      - /var/lib/grafana
    depends_on:
      - prometheus
    image: grafana/grafana
    
