global:
  scrape_timeout: 15s
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    gdg: 'bristol'

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090', 'cadvisor:8080', 'node-exporter:9100']
      
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.17.0.1:8080']
        labels:
          group: 'canary'
    