# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml
#

steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--build-arg=BASE_IMAGE=gcr.io/cloud-builders/javac:8'
  - '--build-arg=MAVEN_VERSION=3.5.4'
  - '--build-arg=SHA256=ce50b1c91364cb77efe3776f756a6d92b76d9038b0a0782f7d53acf1e997a14d'
  - '--tag=eu.gcr.io/$PROJECT_ID/jdk'
  - '--tag=eu.gcr.io/$PROJECT_ID/jdk:jdk8-mvn3.5.4-gcp214'
  - '--tag=eu.gcr.io/$PROJECT_ID/mvn'
  - '--tag=eu.gcr.io/$PROJECT_ID/jdk/mvn:jdk8-mvn3.5.4-gcp214'
  - '--tag=eu.gcr.io/$PROJECT_ID/gcloud'
  - '--tag=eu.gcr.io/$PROJECT_ID/jdk/mvn/gcloud:jdk8-mvn3.5.4-gcp214'
  - '.'
  wait_for: ['-']

images:
- 'eu.gcr.io/$PROJECT_ID/jdk'
- 'eu.gcr.io/$PROJECT_ID/jdk:jdk8-mvn3.5.4-gcp214'
- 'eu.gcr.io/$PROJECT_ID/mvn'
- 'eu.gcr.io/$PROJECT_ID/jdk/mvn:jdk8-mvn3.5.4-gcp214'
- 'eu.gcr.io/$PROJECT_ID/gcloud'
- 'eu.gcr.io/$PROJECT_ID/jdk/mvn/gcloud:jdk8-mvn3.5.4-gcp214'
